services:
    ceww.importer:
        class: AppBundle\Services\Importer
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setTitleCaser, ["@nines.util.title_caser"]]
            - [ setLogger, ["@monolog.logger"]]
            
    ceww.merger:
        class: AppBundle\Services\Merger
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
