services:
    feedback.comment:
        class: FeedbackBundle\Services\CommentService
        arguments: []
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
